### PR TITLE
include-resolutions option added

### PR DESCRIPTION
**Pull request by vagonpidarasov**
Adds the ability to check for resolutions section of package.json
See more about resolutions at: https://yarnpkg.com/lang/en/docs/selective-version-resolutions/

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Can you add a spec to test for this? I don't use `yarn` myself so this is especially important to catch regressions in this functionality.

Note also that there is a required commit message style (`npm install` _should_ have installed the `git` hooks that would have told you this, but I'm guessing that's yet another thing `yarn` fails to do correctly 🤦‍♂️).

**Comment by vagonpidarasov** [comment]
Done.

**Comment by vagonpidarasov** [comment]
I'm sorry, but I'm unable to squash/amend/rebase my master branch. So you either accept my commit messages as they are or reject this PR.

**Pull request merged**
